# Routes principales
controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Route spécifique pour le classement des ambassadeurs
admin_rankings:
  path: /admin/rankings
  controller: App\Controller\Admin\RankingsController::index
